### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Cephas369** [welles/BannerlordCheats#110]
This error happens randomly when I'm walking around the map, my party size is 10,7k
Bannerlord 1.8.0
Mod Version 2.10.3.0 (1.7.2 cause when i use 1.8 my game crashes when i load any save)
```
[- Exception](javascript:;)
Exception information
Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: TaleWorlds.CampaignSystem
CallStack:
at TaleWorlds.CampaignSystem.CharacterDevelopment.DefaultSkillLevelingManager.OnHeroHealedWhileWaiting(MobileParty mobileParty, Int32 healingAmount)
at TaleWorlds.CampaignSystem.Hero.HealByAmountInternal(PartyBase party, Int32 healingAmount, Boolean addXp)
at TaleWorlds.CampaignSystem.CampaignBehaviors.PartyHealCampaignBehavior.HealHeroes(MobileParty mobileParty, Single& heroesHealingValue)
at TaleWorlds.CampaignSystem.CampaignBehaviors.PartyHealCampaignBehavior.TryHealOrWoundParty(MobileParty mobileParty, Boolean isCheckingForPlayerRelatedParty)
at TaleWorlds.CampaignSystem.CampaignBehaviors.PartyHealCampaignBehavior.OnQuarterDailyPartyTick(MobileParty mobileParty)
at TaleWorlds.CampaignSystem.MbEvent`1.InvokeList(EventHandlerRec`1 list, T t)
at TaleWorlds.CampaignSystem.CampaignEvents.QuarterDailyPartyTick(MobileParty mobileParty)
at TaleWorlds.CampaignSystem.CampaignEventDispatcher.QuarterDailyPartyTick(MobileParty party)
at TaleWorlds.CampaignSystem.CampaignPeriodicEventManager.PeriodicTicker`1.PeriodicTickSome(Double timeUnitsElapsed)
at TaleWorlds.CampaignSystem.CampaignPeriodicEventManager.TickPeriodicEvents()
at TaleWorlds.CampaignSystem.Campaign.Tick()
at TaleWorlds.CampaignSystem.GameState.MapState.OnMapModeTick(Single dt)
at TaleWorlds.CampaignSystem.GameState.MapState.OnTick(Single dt)
at TaleWorlds.Core.GameStateManager.OnTick(Single dt)
at TaleWorlds.Core.Game.OnTick(Single dt)
at TaleWorlds.Core.GameManagerBase.OnTick(Single dt)
at TaleWorlds.MountAndBlade.Module.OnApplicationTick_Patch10(Module this, Single dt)
at TaleWorlds.DotNet.Managed.ApplicationTick_Patch1(Single dt)
```
```
[- Involved Modules](javascript:;)
[Cheats](javascript:;)
Method: static System.Void BannerlordCheats.Patches.General.EnableHotkeysAddItems::OnApplicationTick()
Frame: TaleWorlds.MountAndBlade.Module.OnApplicationTick_Patch10 at offset 1875 in file:line:column :0:0
Method: static System.Void BannerlordCheats.Patches.General.EnableHotkeysCharacterAttributes::OnApplicationTick()
Frame: TaleWorlds.MountAndBlade.Module.OnApplicationTick_Patch10 at offset 1875 in file:line:column :0:0
Method: static System.Void BannerlordCheats.Patches.General.EnableHotkeysCharacterPoints::OnApplicationTick()
Frame: TaleWorlds.MountAndBlade.Module.OnApplicationTick_Patch10 at offset 1875 in file:line:column :0:0
Method: static System.Void BannerlordCheats.Patches.General.EnableHotkeysInfluence::OnApplicationTick()
Frame: TaleWorlds.MountAndBlade.Module.OnApplicationTick_Patch10 at offset 1875 in file:line:column :0:0
Method: static System.Void BannerlordCheats.Patches.General.EnableHotkeysMoney::OnApplicationTick()
Frame: TaleWorlds.MountAndBlade.Module.OnApplicationTick_Patch10 at offset 1875 in file:line:column :0:0
Method: static System.Void BannerlordCheats.Patches.General.EnableHotkeysTroopCount::OnApplicationTick()
Frame: TaleWorlds.MountAndBlade.Module.OnApplicationTick_Patch10 at offset 1875 in file:line:column :0:0
Method: static System.Void BannerlordCheats.Patches.General.EnableHotkeysTroopExperience::OnApplicationTick()
Frame: TaleWorlds.MountAndBlade.Module.OnApplicationTick_Patch10 at offset 1875 in file:line:column :0:0
Method: static System.Void BannerlordCheats.Patches.Combat.HealthRegeneration::OnApplicationTick(System.Single dt)
Frame: TaleWorlds.MountAndBlade.Module.OnApplicationTick_Patch10 at offset 1875 in file:line:column :0:0
Method: static System.Void BannerlordCheats.Patches.Combat.PartyHealthRegeneration::OnApplicationTick(System.Single dt)
Frame: TaleWorlds.MountAndBlade.Module.OnApplicationTick_Patch10 at offset 1875 in file:line:column :0:0
```

**Comment by welles** [comment]
Fixed by update
